[project]
name = "gen-ai"
version = "0.1.0"
description = "AI Portfolio Hub"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=0.2.0",
    "langchain-community",
    "langchain-core",
    "langchain-google-genai",
    "langchain-groq",
    "langchain-mistralai",
    "langchain-huggingface",
    "google-generativeai",
    "groq",
    "mistralai",
    "python-dotenv",
    "streamlit",
    "requests"
]